source 'https://github.com/CocoaPods/Specs.git'

target 'CUPMobileLibrary', :exclusive => true do
  pod "CUPMobileLibrary", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CUPMobileLibrary", :path => "../"

#  pod 'Specta', '~> 0.2.1'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
end
